name: CI
on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node.js ${{ matrix.version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Clean install dependencies and test
        run: npm cit
      - name: Publish coverage to coveralls
        run: npm run coveralls